### PR TITLE
Fix merge_sort.jl

### PR DESCRIPTION
**Pull request by MarcMush**

### CODE REVIEW

**Comment by stefankober** [comment]
@MarcMush , yes, that's it. I just wanted to open the same PR ;)

**Comment by MarcMush** [comment]
Yeah, I'm a bit ashamed, I added this algorithm here and I don't know how I commited such an obviously non-working algorithm

**Comment by stefankober** [comment]
Considering they helped me greatly understand Julia you shouldn’t. I love it & thanks for the work!

**Comment by MarcMush** [comment]
@abranhe can you merge this ?

**Review by abranhe — APPROVED** [review]
Thanks so much for your contribution to [The All ▲lgorithms Project](https://github.com/allalgorithms). Without people like you submitting Pull Requests we couldn't run this project. You rock!

**Comment by MarcMush** [comment]
thanks

**Pull request merged**
